# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Karthik!"

In [5]:
print(s.split())

['Hi', 'there', 'Karthik!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [11]:
print("The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print( d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [26]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [27]:
A=np.array([0,0,0,0,0,0,0,0,0,0])
Ar=np.array([5,5,5,5,5,5,5,5,5,5])
print(A)
print(Ar)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
Arr2=np.arange(20,35,2)
print(Arr2)

[20 22 24 26 28 30 32 34]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [44]:
import pandas as pd
df={
    "Name":['a','b','c'],
    "Marks":[10,20,30]
}
dataframe = pd.DataFrame(df)
print(dataframe)

  Name  Marks
0    a     10
1    b     20
2    c     30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [45]:
d=pd.date_range(start='1/1/2023', end='10/02/2023')

In [46]:
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [41]:
df = pd.DataFrame(lists, columns =['F_No', 'Name', 'L_No'],
                                           dtype = int) 
print(df)

   F_No Name  L_No
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
